# 서버 포트 설정
server:
  port: 8080

# Mysql 데이터 베이스 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trust_trade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

nts:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/validate
    service-key: 7o9mUfbhRmqCpyqZYFTXMNMrZNoSJH2D3mbgjGcMTgLSCEunxEsUpCgqIKgYUx%2B4Y0YBgfwRSFNBCOs%2F5WBcKA%3D%3D

kakao:
  api:
    service-key: 2825961cc8fb6c3773683f50fc3b6b7a


# 로깅 설정
logging:
  level:
    org.hibernate.tool.schema.internal.SchemaDropperImpl: TRACE
    org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator: TRACE